### ISSUE TITLE
[Feature] Add Debian support for aarch64.

### ISSUE THREAD

**Issue by Conan-16** [beringresearch/macpine#181]
**Is your feature request related to a problem? Please describe.**
I'm using a M1 Mac, and when I try to launch a debian_11.3.0 image, no matter I use "--arch aarch64" or not, it fails with "unable to download debian_11.3.0-aarch64.qcow2 for aarch64: requested image download is not supported: StatusCode 404"

But when I use "--arch x86_64", it starts retrieving image and booting successfully. 

**Describe the solution you'd like**
Add Debian support for aarch64. 

**Describe alternatives you've considered**
Or tell users there is no supported Debian images for aarch64 now, if users still want to launch a Debian image, please use "--arch x86_64" manually instead. 

**Additional context**
Also, it would be great if users can know which image are supported, it also helps users to launch an image more easily. For now, I know only alpine and Debian are supported by typing a random image name.

**Comment by idroz** [comment]
Hi - thanks for flagging this.

This lack of transparency on which images are available is due to our initial hesitation about opening up macpine to things other than Alpine linux.

The "primary" usecase that we envisage for macpine is that Alpine linux is used as a light-weight layer (150MB install vs. Debians 900MB) on top of MacOS that runs LXC containers locally. These containers are then accessible either through LXD or incus clients. The user can then add and configure whatever OS they require.

Of course Alpine does have drawbacks compared to systems like Debian, hence our hesitation at this stage.

Therefore, we don't really see Macpine as  a VM management software - there are quite a few of those now for Macs - UTM (https://mac.getutm.app), tart (https://tart.run), lima (https://github.com/lima-vm/lima).

I'd be really interested to hear the counter-argument to this - especially in light of some minimal Debian distro.

**Comment by Conan-16** [comment]
Thanks for replying. I requested Debian support for aarch64 because I need a lightweight Debian environment to setup my home-assistant supervised server without buying a new device. 

I hope it could run quietly as a docker container, and it seems macpine is my best choice because many other softwares either have a GUI which I don't need, or they just don't support Debian like Multipass. 

Now I can understand your hesitation, Alpine is much lighter than Debian in deed. But I probably still using macpine to setup a Debian environment since home-assistant does not support any other Linux not even a modified Debian environment. So I hope you won't stop Debian support for X86_64 currently we have at least.

Thanks for your wonderful work on macpine.

**Comment by idroz** [comment]
That's a cool use case. I think the easiest way to run debian on macpine is through either LXD or Incus. We've got quickstart guides on how to set those up.

Incus: https://beringresearch.github.io/macpine/incus_macpine/
LXD: https://beringresearch.github.io/macpine/lxd_macpine/

You can also give a macpine VM its own IP using mac's vmnet-shared mode. This requires macpine to be run as sudo:

```bash
sudo alpine launch --name first  --shared
```

The machine's IP is listed using `alpine info first`

**Comment by Conan-16** [comment]
Currently, I'm using ifconfig on my Mac to get my VM's IP. Giving VM an own IP and checking IP by alpine info ⌘ will help me a lot, but when I tried run macpine as sudo with --shared, it returns Error: unknown flag: --shared.

**Comment by idroz** [comment]
This feature is available with the latest macpine release. If you’re using brew to install macpine,

‘’’
brew update; brew install macpine 
‘’’

otherwise you can grab the latest binary from macpine releases.

**Comment by idroz** [comment]
will close as probably addressed
